<?php
declare(strict_types=1);
session_name('blujay_interviews'); session_start();
$configPath = __DIR__ . '/config.php';
$cfg = is_file($configPath) ? require $configPath : [];
foreach (['db_host' => 'DB_HOST', 'db_name' => 'DB_NAME', 'db_user' => 'DB_USER', 'db_pass' => 'DB_PASS'] as $key => $environmentVariable) {
	$value = getenv($environmentVariable);
	if ($value !== false) $cfg[$key] = $value;
}
try { $db = new PDO("mysql:host={$cfg['db_host']};dbname={$cfg['db_name']};charset=utf8mb4", $cfg['db_user'], $cfg['db_pass'], [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); }
catch (Throwable $e) { http_response_code(500); exit('Database connection failed. Check config.php.'); }
function h($value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function url(string $path=''): string { return '/'.ltrim($path,'/'); }
function go(string $path): never { header('Location: '.url($path)); exit; }
function token(): string { if(empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(32)); return $_SESSION['csrf']; }
function verify(): void { if(!hash_equals($_SESSION['csrf']??'', $_POST['csrf']??'')) { http_response_code(400); exit('Please reload and try again.'); } }
function me(PDO $db): ?array { if(empty($_SESSION['uid'])) return null; $s=$db->prepare('SELECT * FROM users WHERE id=? AND is_active=1');$s->execute([$_SESSION['uid']]);return $s->fetch()?:null; }
function need(PDO $db, array $roles=[]): array { $u=me($db); if(!$u) go('login'); if($roles && !in_array($u['role'],$roles,true)){http_response_code(403);exit('Access denied.');} return $u; }
function flash(string $text): void { $_SESSION['flash']=$text; }
function layout(string $title, string $body, ?array $user=null): never { $notice=$_SESSION['flash']??'';unset($_SESSION['flash']); echo '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.h($title).' | BluJay</title><style>body{margin:0;background:#f4f7fb;color:#16315a;font:15px Inter,Arial,sans-serif}nav{background:#fff;padding:16px 5%;display:flex;justify-content:space-between;border-bottom:1px solid #dde6f2}a{color:#1766cc;text-decoration:none}main{max-width:1050px;margin:32px auto;padding:0 18px}.card{background:#fff;border:1px solid #dde6f2;border-radius:16px;padding:22px;margin:16px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.btn,button{background:#176bda;color:white;border:0;border-radius:9px;padding:11px 15px;font-weight:700;cursor:pointer}.danger{background:#b9364b}.muted{color:#637590}.notice{background:#eaf5ef;padding:12px;border-radius:8px}input,select{width:100%;box-sizing:border-box;padding:11px;border:1px solid #cbd8e8;border-radius:8px;margin:6px 0 14px}table{width:100%;border-collapse:collapse}td,th{padding:12px;border-bottom:1px solid #e7edf5;text-align:left}@media(max-width:600px){main{margin:18px auto}table{font-size:12px}}</style></head><body><nav><strong>🟦 BluJay Interviews</strong><span>'.($user? h($user['name']).' · <a href="'.url('logout').'">Sign out</a>':'').'</span></nav><main>'.($notice?'<p class="notice">'.h($notice).'</p>':'').$body.'</main></body></html>';exit; }
$path=trim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/');
if($path===''||$path==='login') { if($_SERVER['REQUEST_METHOD']==='POST'){verify();$s=$db->prepare('SELECT * FROM users WHERE email=? AND is_active=1');$s->execute([strtolower(trim($_POST['email']??''))]);$u=$s->fetch();if($u && password_verify($_POST['password']??'', $u['password'])){$_SESSION['uid']=$u['id'];go($u['force_password_change']?'password':'dashboard');}flash('Invalid email or password.');go('login');} layout('Login','<section class="card" style="max-width:420px;margin:auto"><h1>Welcome back</h1><form method="post"><input type="hidden" name="csrf" value="'.token().'"><label>Email</label><input required type="email" name="email"><label>Password</label><input required type="password" name="password"><button>Sign in</button></form></section>'); }
if($path==='logout'){session_destroy();go('login');}
$user=need($db);
if($user['force_password_change']&&$path!=='password'){go('password');}
if($path==='password'){if($_SERVER['REQUEST_METHOD']==='POST'){verify();$p=$_POST['password']??'';if(strlen($p)<8||$p!==($_POST['confirm']??'')){flash('Use a matching password with at least 8 characters.');go('password');}$db->prepare('UPDATE users SET password=?,force_password_change=0 WHERE id=?')->execute([password_hash($p,PASSWORD_DEFAULT),$user['id']]);flash('Password updated.');go('dashboard');}layout('Set password','<section class="card" style="max-width:460px;margin:auto"><h1>Set your password</h1><form method="post"><input type="hidden" name="csrf" value="'.token().'"><input name="password" required minlength="8" type="password" placeholder="New password"><input name="confirm" required minlength="8" type="password" placeholder="Confirm password"><button>Update password</button></form></section>',$user);}
if($path==='slots'){need($db,['admin','hr']);if($_SERVER['REQUEST_METHOD']==='POST'){verify();$date=$_POST['date']??'';$start=$_POST['start']??'';$end=$_POST['end']??'';$license=(int)($_POST['license']??0);if(!$date||!$start||!$end||!$license||$start>=$end){flash('Enter a valid date, license, and time range.');go('slots');}$s=$db->prepare('INSERT INTO interview_slots(license_id,interview_date,start_time,end_time,status) VALUES(?,?,?,?,\'available\')');$s->execute([$license,$date,$start,$end]);flash('Interview slot created.');go('slots');}$licenses=$db->query('SELECT * FROM licenses ORDER BY name')->fetchAll();$options='';foreach($licenses as $l)$options.='<option value="'.h($l['id']).'">'.h($l['name']).'</option>';$today=$db->query("SELECT s.*,l.name license FROM interview_slots s JOIN licenses l ON l.id=s.license_id WHERE s.interview_date>=CURDATE() ORDER BY s.interview_date,s.start_time LIMIT 40")->fetchAll();$rows='';foreach($today as $s)$rows.='<tr><td>'.h($s['interview_date']).'</td><td>'.h(date('g:i A',strtotime($s['start_time']))).'–'.h(date('g:i A',strtotime($s['end_time']))).'</td><td>'.h($s['license']).'</td><td>'.h($s['status']).'</td></tr>';layout('Interview slots','<h1>Interview slots</h1><section class="card"><h2>Create slot</h2><form method="post"><input type="hidden" name="csrf" value="'.token().'"><div class="grid"><input required name="date" type="date"><input required name="start" type="time"><input required name="end" type="time"><select name="license" required><option value="">Select license</option>'.$options.'</select></div><button>Create slot</button></form></section><section class="card"><table><tr><th>Date</th><th>Time</th><th>License</th><th>Status</th></tr>'.$rows.'</table></section>',$user);}
if($path==='book'){need($db,['candidate']);if($_SERVER['REQUEST_METHOD']!=='POST'){go('dashboard');}verify();$slot=(int)($_POST['slot']??0);try{$db->beginTransaction();$q=$db->prepare("SELECT id FROM interview_slots WHERE id=? AND status='available' FOR UPDATE");$q->execute([$slot]);if(!$q->fetch())throw new RuntimeException('That slot is no longer available.');$count=$db->prepare("SELECT COUNT(*) FROM bookings b JOIN interview_slots s ON s.id=b.slot_id WHERE b.user_id=? AND s.interview_date=(SELECT interview_date FROM interview_slots WHERE id=?) AND b.booking_status='confirmed'");$count->execute([$user['id'],$slot]);if((int)$count->fetchColumn()>=2)throw new RuntimeException('You already have two confirmed bookings on that date.');$db->prepare("INSERT INTO bookings(user_id,slot_id,company_name,technology,interview_round,remarks) VALUES(?,?,?,?,?,?)")->execute([$user['id'],$slot,trim($_POST['company']??''),trim($_POST['technology']??''),trim($_POST['round']??''),trim($_POST['remarks']??'')]);$db->prepare("UPDATE interview_slots SET status='booked' WHERE id=?")->execute([$slot]);$db->commit();flash('Interview slot booked successfully.');}catch(Throwable $e){if($db->inTransaction())$db->rollBack();flash($e->getMessage());}go('dashboard');}
if($path==='dashboard'){if(in_array($user['role'],['admin','hr'],true)){$today=$db->query("SELECT b.*,u.name,s.start_time,s.end_time FROM bookings b JOIN users u ON u.id=b.user_id JOIN interview_slots s ON s.id=b.slot_id WHERE s.interview_date=CURDATE() ORDER BY s.start_time")->fetchAll();$rows='';foreach($today as $b)$rows.='<tr><td>'.h(date('g:i A',strtotime($b['start_time']))).'–'.h(date('g:i A',strtotime($b['end_time']))).'</td><td>'.h($b['name']).'</td><td>'.h($b['technology']?:'—').'</td><td>'.h($b['booking_status']).'</td></tr>';layout('Dashboard','<h1>Today’s interviews</h1><p class="muted">10:00 AM – 7:00 PM · India Standard Time</p><section class="card"><table><tr><th>Time</th><th>Candidate</th><th>Technology</th><th>Status</th></tr>'.($rows?:'<tr><td colspan="4">No interviews today.</td></tr>').'</table></section><p><a class="btn" href="'.url('slots').'">Create & view slots</a> <a class="btn" href="'.url('candidates').'">Manage candidates</a> '.($user['role']==='admin'?'<a class="btn" href="'.url('admins').'">Manage admins</a>':'').'</p>',$user);}else{$bookings=$db->prepare("SELECT b.*,s.interview_date,s.start_time,s.end_time,l.name license FROM bookings b JOIN interview_slots s ON s.id=b.slot_id JOIN licenses l ON l.id=s.license_id WHERE b.user_id=? ORDER BY s.interview_date DESC,s.start_time DESC");$bookings->execute([$user['id']]);$bookingRows='';foreach($bookings as $b)$bookingRows.='<tr><td>'.h($b['interview_date']).'</td><td>'.h(date('g:i A',strtotime($b['start_time']))).'–'.h(date('g:i A',strtotime($b['end_time']))).'</td><td>'.h($b['technology']?:'—').'</td><td>'.h($b['booking_status']).'</td></tr>';$slots=$db->query("SELECT s.*,l.name license FROM interview_slots s JOIN licenses l ON l.id=s.license_id WHERE s.status='available' AND s.interview_date>=CURDATE() ORDER BY s.interview_date,s.start_time LIMIT 30")->fetchAll();$options='';foreach($slots as $s)$options.='<option value="'.h($s['id']).'">'.h($s['interview_date'].' · '.date('g:i A',strtotime($s['start_time'])).' · '.$s['license']).'</option>';layout('Dashboard','<h1>Welcome, '.h($user['name']).'</h1><section class="card"><h2>Book interview slot</h2><form method="post" action="'.url('book').'"> <input type="hidden" name="csrf" value="'.token().'"><select name="slot" required><option value="">Select a time</option>'.$options.'</select><div class="grid"><input required name="company" placeholder="Company"><input required name="technology" placeholder="Technology"><input required name="round" placeholder="Interview round"></div><input name="remarks" placeholder="Remarks (optional)"><button>Book interview</button></form></section><section class="card"><h2>Your bookings</h2><table><tr><th>Date</th><th>Time</th><th>Technology</th><th>Status</th></tr>'.($bookingRows?:'<tr><td colspan="4">No bookings yet.</td></tr>').'</table></section>',$user);}}
if($path==='candidates'){need($db,['admin','hr']);if($_SERVER['REQUEST_METHOD']==='POST'){verify();if(($_POST['action']??'')==='add'){$db->prepare("INSERT INTO users(name,email,password,role,is_active,force_password_change) VALUES(?,?,?,'candidate',1,1)")->execute([trim($_POST['name']),strtolower(trim($_POST['email'])),password_hash($_POST['password'],PASSWORD_DEFAULT)]);flash('Candidate created.');}elseif(($_POST['action']??'')==='delete'){$db->prepare("DELETE FROM users WHERE id=? AND role='candidate'")->execute([(int)$_POST['id']]);flash('Candidate deleted.');}go('candidates');}$rows='';foreach($db->query("SELECT * FROM users WHERE role='candidate' ORDER BY id DESC") as $c)$rows.='<tr><td>'.h($c['name']).'</td><td>'.h($c['email']).'</td><td>'.($c['is_active']?'Active':'Inactive').'</td><td><form method="post"><input type="hidden" name="csrf" value="'.token().'"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="'.h($c['id']).'"><button class="danger">Delete</button></form></td></tr>';layout('Candidates','<h1>Manage candidates</h1><section class="card"><h2>Add candidate</h2><form method="post"><input type="hidden" name="csrf" value="'.token().'"><input type="hidden" name="action" value="add"><div class="grid"><input required name="name" placeholder="Full name"><input required type="email" name="email" placeholder="Email"><input required minlength="8" type="password" name="password" placeholder="Temporary password"></div><button>Add candidate</button></form></section><section class="card"><table><tr><th>Name</th><th>Email</th><th>Status</th><th></th></tr>'.$rows.'</table></section>',$user);}
if($path==='admins'){need($db,['admin']);if($_SERVER['REQUEST_METHOD']==='POST'){verify();$db->prepare("INSERT INTO users(name,email,password,role,is_active,force_password_change) VALUES(?,?,?,'admin',1,1)")->execute([trim($_POST['name']),strtolower(trim($_POST['email'])),password_hash($_POST['password'],PASSWORD_DEFAULT)]);flash('Admin created.');go('admins');}$rows='';foreach($db->query("SELECT name,email FROM users WHERE role='admin' ORDER BY id") as $a)$rows.='<li>'.h($a['name']).' · '.h($a['email']).'</li>';layout('Admins','<h1>Manage admins</h1><section class="card"><ul>'.$rows.'</ul></section><section class="card"><h2>Add admin</h2><form method="post"><input type="hidden" name="csrf" value="'.token().'"><input required name="name" placeholder="Full name"><input required type="email" name="email" placeholder="Email"><input required minlength="8" type="password" name="password" placeholder="Temporary password"><button>Create admin</button></form></section>',$user);}
http_response_code(404);layout('Not found','<h1>Page not found</h1><a href="'.url('dashboard').'">Go to dashboard</a>',$user);
